# Generated by Django 6.0.3 on 2026-04-06 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("descricao", models.TextField(blank=True)),
                (
                    "certificado",
                    models.FileField(blank=True, null=True, upload_to="formacoes/"),
                ),
                ("link", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["-ano"],
            },
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(max_length=20)),
                ("instituicao", models.CharField(max_length=200)),
                ("ano_inicio", models.IntegerField()),
                ("descricao", models.TextField(blank=True)),
                ("link", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="licenciatura/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data", models.DateField(auto_now_add=True)),
                (
                    "fotografia",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                ("erros_encontrados", models.TextField(blank=True)),
                ("decisoes_tomadas", models.TextField(blank=True)),
                ("uso_ia", models.TextField(blank=True)),
                ("entidade_relacionada", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("link_oficial", models.URLField(blank=True)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("intermedio", "Intermédio"),
                            ("avancado", "Avançado"),
                        ],
                        default="basico",
                        max_length=20,
                    ),
                ),
                ("categoria", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("autor", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("resumo", models.TextField(blank=True)),
                ("orientador", models.CharField(blank=True, max_length=200)),
                ("link", models.URLField(blank=True)),
                ("destaque", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("ano", models.IntegerField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("video_url", models.URLField(blank=True)),
                ("repositorio_github", models.URLField(blank=True)),
                ("conceitos_aplicados", models.TextField(blank=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                (
                    "projetos",
                    models.ManyToManyField(blank=True, to="portfolio.projeto"),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(blank=True, max_length=20)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("ects", models.IntegerField(default=6)),
                ("descricao", models.TextField(blank=True)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="ucs/")),
                ("docente", models.CharField(blank=True, max_length=200)),
                ("link_docente", models.URLField(blank=True)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="unidade_curricular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projetos",
                to="portfolio.unidadecurricular",
            ),
        ),
    ]
