# Generated by Django 6.0.3 on 2026-04-07 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("link_pagina_lusofona", models.URLField(blank=True)),
                (
                    "fotografia",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
                ("departamento", models.CharField(blank=True, max_length=200)),
                ("especialidade", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="docente",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="link_docente",
        ),
        migrations.AddField(
            model_name="formacao",
            name="competencias",
            field=models.ManyToManyField(
                blank=True, related_name="formacoes", to="portfolio.competencia"
            ),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="projetos",
            field=models.ManyToManyField(
                blank=True, related_name="competencias", to="portfolio.projeto"
            ),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="competencias", to="portfolio.tecnologia"
            ),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="docentes",
            field=models.ManyToManyField(
                blank=True, related_name="ucs", to="portfolio.docente"
            ),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tfcs",
                to="portfolio.docente",
            ),
        ),
    ]
