# Generated by Django 6.0.3 on 2026-04-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_docente_remove_unidadecurricular_docente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="colaboradores",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="projeto",
            name="competencias_adquiridas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projeto",
            name="link_deploy",
            field=models.URLField(blank=True),
        ),
    ]
